version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes: 
      - ./data:/data/db
    ports: 
      - "27018:27018"
  api:
    container_name: api-container
    build: .
    image: clean-ts-api
    restart: always
    command: yarn start
    volumes: 
      - ./dist:/usr/src/clean-ts-api/dist
    ports:
      - "5050:5050"
    links: 
      - mongo

