version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes: 
      - ./data:/data/db
    ports: 
      - "27018:27018"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/clean-ts-api
    restart: always
    command: bash -c "yarn install --only=prod && yarn debug"
    volumes: 
      - ./dist:/usr/src/clean-ts-api/dist
      - ./package.json:/usr/src/clean-ts-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links: 
      - mongo

